export default {
  LOGIN: "Login",
  REGISTER: "Register",
  HOME: "Home",
  CONNECTUS: "ConnectUs",
  HABITS: "Habits",
  PROGRAMTASKS: "ProgramTasks",
  SHOP: "Shop",
  THEME: "Theme",
  TEAM: "Team",
  USER: "User",
  GAGE: "Gage",
  ABOUT: "About",
  WELCOME: "Welcome",
};
