export const GlobalStyles = {
  colors: {
    primary: "#FFF39E",
    background: "rgb(27, 27, 27)",
    secondary: "#ffffff",
    todo: "#FCB1B1",
    done: "#C2FFC8",
    deleting: "#ff0033",
    presentation: "lightblue",
    muted: "#515151",
    text: "#ffffff",
    h1: "#ffffff",
    h2: "#ffffff",
    h3: "#ffffff",
    h4: "#ffffff",
    h5: "#ffffff",
    h6: "#ffffff",
  },
  reactNative: {
    primary: "rgb(255, 255, 255)",
    background: "rgb(0, 0, 0)",
    card: "rgb(0, 0, 0)",
    text: "rgb(255, 255, 255)",
    border: "rgb(0, 0, 0)",
    notification: "rgb(0, 0, 0)",
    darktheme: false,
  },
  fontsSize: {
    h1: 30,
    h2: 26,
    h3: 22,
    h4: 18,
    h5: 16,
    h6: 14,
    text: 20,
    dayText: 20,
  },
  buttons: {
    xl: "XL",
    lg: "LG",
    md: "MD",
    sm: "SM",
    xs: "XS",
  },
};
